use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Монитор использования Claude Code",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    fifteen_seconds: "15 секунд",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    models: "Модели",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Настройки",
    start_with_windows: "Запускать вместе с Windows",
    reset_position: "Сбросить позицию",
    language: "Язык",
    system_default: "Системный по умолчанию",
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Показать виджет",
    session_window: "5ч",
    weekly_window: "7д",
    now: "сейчас",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    token_expired_title: "Ошибка авторизации Claude Code",
    token_expired_body: "Запустите 'claude' в терминале, затем используйте '/login' и следуйте инструкциям. После этого обновите или перезапустите приложение.",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    antigravity_token_expired_title: "Ошибка авторизации Antigravity",
    antigravity_token_expired_body: "Откройте Antigravity и войдите снова. После этого обновите или перезапустите приложение.",
    codex_window_title: "Монитор использования Codex",
    antigravity_window_title: "Монитор использования Antigravity",
    kimi_model: "Kimi",
    kimi_window_title: "Монитор использования Kimi",
    kimi_token_expired_title: "Ошибка авторизации Kimi",
    kimi_token_expired_body: "Срок действия входа в Kimi истёк. Сохраните новый refresh-токен в kimi.json, затем обновите или перезапустите приложение.",
    copilot_model: "Copilot",
    copilot_window_title: "Монитор использования Copilot",
    copilot_token_expired_title: "Ошибка авторизации Copilot",
    copilot_token_expired_body: "Проверьте copilot.json в папке приложения. Токену нужен доступ на чтение биллинга организации, и он не должен быть просрочен.",
    bar_length: "Длина полосы",
    bar_length_auto: "Авто",
};
